"jobs":
  "run-on-env":
    "permissions":
      "contents": "read"
      "pull-requests": "read"
    "runs-on":
    - "ubuntu-latest"
    "steps":
    - "name": "checkout"
      "uses": "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11"
      "with":
        "fetch-depth": 0
    - "name": "check for ${{ inputs.environment }}"
      "run": "[ ${{ inputs.environment }} != \"dev\" ]"
"on":
  "workflow_call":
    "inputs":
      "environment":
        "required": true
        "type": "string"
