"jobs":
  "all-passed":
    "if": "always()"
    "needs":
    - "generate-matrix"
    - "call-workflows"
    "runs-on":
    - "ubuntu-latest"
    "steps":
    - "name": "check all jobs for approval"
      "uses": "re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe"
      "with":
        "allowed-skips": "generate-matrix"
        "jobs": "${{ toJSON(needs) }}"
  "call-workflows":
    "if": true
    "needs": []
    "secrets": "inherit"
    "strategy":
      "matrix":
        "environments":
        - "dev"
        - "staging"
        - "prod"
    "uses": "./.github/workflows/called.yaml"
    "with":
      "environment": "${{ matrix.environments }}"
  "generate-matrix":
    "if": false
    "outputs":
      "matrix": "${{ steps.generate.outputs.matrix }}"
    "runs-on":
    - "ubuntu-latest"
    "steps":
    - "name": "checkout"
      "uses": "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11"
      "with":
        "fetch-depth": 0
    - "id": "generate"
      "name": "generate matrix"
      "run": |
        output="$(for i in dev staging prod ; do [[ -z $(git diff --name-only origin/master...HEAD | grep -E "stacks/${i}") ]] || echo $i ; done)"
        [ -z "$output" ] || echo "matrix=[\""${output//[ ]/\", \"}"\"]" >> "$GITHUB_OUTPUT"
"name": "main"
"on":
  "pull_request": {}
"permissions":
  "contents": "read"
  "pull-requests": "read"
